export const GET_CONTENT = "GET_CONTENT";
export const ADD_CONTENT = "ADD_CONTENT";
export const DELETE_CONTENT = "DELETE_CONTENT";
export const UPDATE_CONTENT = "UPDATE_CONTENT";

export const ADD_TO_HISTORY = "ADD_TO_HISTORY";

// Filter
export const FILTER_BY_CATEGORY = "FILTER_BY_CATEGORY";
export const REMOVE_FILTER = "REMOVE_FILTER";
